name := "CaesarCipher"
version := "0.1"
scalaVersion := "2.13.1"
libraryDependencies += "com.typesafe.akka" %% "akka-actor-typed" % "2.6.0"
libraryDependencies += "org.slf4j" % "slf4j-simple" % "1.7.29"